import { CryptoAsset, PopularityTier, Sector, Chain } from './types';

export const NEW_ASSETS: CryptoAsset[] = [
  // --- TIER A: Top 10 (Already in constants, but ensuring completeness) ---
  { id: 'btc', name: 'BITCOIN', symbol: 'BTC', color: '#F7931A', tier: PopularityTier.A, sector: Sector.L1, chain: Chain.BITCOIN },
  { id: 'eth', name: 'ETHEREUM', symbol: 'ETH', color: '#627EEA', tier: PopularityTier.A, sector: Sector.L1, chain: Chain.ETHEREUM },
  { id: 'usdt', name: 'TETHER', symbol: 'USDT', color: '#26A17B', tier: PopularityTier.A, sector: Sector.STABLECOIN, chain: Chain.MULTICHAIN },
  { id: 'bnb', name: 'BINANCE', symbol: 'BNB', color: '#F3BA2F', tier: PopularityTier.A, sector: Sector.EXCHANGE, chain: Chain.BSC },
  { id: 'sol', name: 'SOLANA', symbol: 'SOL', color: '#14F195', tier: PopularityTier.A, sector: Sector.L1, chain: Chain.SOLANA },
  { id: 'xrp', name: 'RIPPLE', symbol: 'XRP', color: '#23292F', tier: PopularityTier.A, sector: Sector.L1, chain: Chain.OTHER },
  { id: 'usdc', name: 'USDC', symbol: 'USDC', color: '#2775CA', tier: PopularityTier.A, sector: Sector.STABLECOIN, chain: Chain.MULTICHAIN },
  { id: 'ada', name: 'CARDANO', symbol: 'ADA', color: '#0033AD', tier: PopularityTier.A, sector: Sector.L1, chain: Chain.OTHER },
  { id: 'avax', name: 'AVALANCHE', symbol: 'AVAX', color: '#E84142', tier: PopularityTier.A, sector: Sector.L1, chain: Chain.OTHER },
  { id: 'doge', name: 'DOGECOIN', symbol: 'DOGE', color: '#C2A633', tier: PopularityTier.A, sector: Sector.MEME, chain: Chain.OTHER },

  // --- TIER B: Majors & Staples (Rank 11-50) ---
  { id: 'dot', name: 'POLKADOT', symbol: 'DOT', color: '#E6007A', tier: PopularityTier.B, sector: Sector.L1, chain: Chain.DOT },
  { id: 'trx', name: 'TRON', symbol: 'TRX', color: '#FF0013', tier: PopularityTier.B, sector: Sector.L1, chain: Chain.OTHER },
  { id: 'matic', name: 'POLYGON', symbol: 'MATIC', color: '#8247E5', tier: PopularityTier.B, sector: Sector.L2, chain: Chain.ETHEREUM },
  { id: 'link', name: 'CHAINLINK', symbol: 'LINK', color: '#2A5ADA', tier: PopularityTier.B, sector: Sector.ORACLE, chain: Chain.MULTICHAIN },
  { id: 'ton', name: 'TONCOIN', symbol: 'TON', color: '#0098EA', tier: PopularityTier.B, sector: Sector.L1, chain: Chain.OTHER },
  { id: 'wbtc', name: 'WRAPPED BTC', symbol: 'WBTC', color: '#F09242', tier: PopularityTier.B, sector: Sector.DEFI, chain: Chain.BITCOIN },
  { id: 'shib', name: 'SHIBA INU', symbol: 'SHIB', color: '#FFA409', tier: PopularityTier.B, sector: Sector.MEME, chain: Chain.ETHEREUM },
  { id: 'ltc', name: 'LITECOIN', symbol: 'LTC', color: '#BFBBBB', tier: PopularityTier.B, sector: Sector.L1, chain: Chain.OTHER },
  { id: 'dai', name: 'DAI', symbol: 'DAI', color: '#F5AC37', tier: PopularityTier.B, sector: Sector.STABLECOIN, chain: Chain.ETHEREUM },
  { id: 'bch', name: 'BITCOIN CASH', symbol: 'BCH', color: '#8DC351', tier: PopularityTier.B, sector: Sector.L1, chain: Chain.OTHER },
  { id: 'atom', name: 'COSMOS', symbol: 'ATOM', color: '#2E3148', tier: PopularityTier.B, sector: Sector.L1, chain: Chain.COSMOS },
  { id: 'uni', name: 'UNISWAP', symbol: 'UNI', color: '#FF007A', tier: PopularityTier.B, sector: Sector.DEX, chain: Chain.ETHEREUM },
  { id: 'leo', name: 'LEO TOKEN', symbol: 'LEO', color: '#F7931A', tier: PopularityTier.C, sector: Sector.EXCHANGE, chain: Chain.OTHER },
  { id: 'xlm', name: 'STELLAR', symbol: 'XLM', color: '#14B6E7', tier: PopularityTier.B, sector: Sector.L1, chain: Chain.OTHER },
  { id: 'okb', name: 'OKB', symbol: 'OKB', color: '#2D61AE', tier: PopularityTier.C, sector: Sector.EXCHANGE, chain: Chain.OTHER },
  { id: 'etc', name: 'ETHEREUM LC', symbol: 'ETC', color: '#328332', tier: PopularityTier.B, sector: Sector.L1, chain: Chain.ETHEREUM }, // "LC" hint for classic
  { id: 'xmr', name: 'MONERO', symbol: 'XMR', color: '#FF6600', tier: PopularityTier.B, sector: Sector.L1, chain: Chain.OTHER },
  { id: 'fil', name: 'FILECOIN', symbol: 'FIL', color: '#0090FF', tier: PopularityTier.B, sector: Sector.INFRA, chain: Chain.OTHER },
  { id: 'ldo', name: 'LIDO DAO', symbol: 'LDO', color: '#00A3FF', tier: PopularityTier.C, sector: Sector.DEFI, chain: Chain.ETHEREUM },
  { id: 'hbar', name: 'HEDERA', symbol: 'HBAR', color: '#222222', tier: PopularityTier.C, sector: Sector.L1, chain: Chain.OTHER },
  { id: 'apt', name: 'APTOS', symbol: 'APT', color: '#2DD8A7', tier: PopularityTier.B, sector: Sector.L1, chain: Chain.OTHER },
  { id: 'arb', name: 'ARBITRUM', symbol: 'ARB', color: '#2D374B', tier: PopularityTier.B, sector: Sector.L2, chain: Chain.ETHEREUM },
  { id: 'vet', name: 'VECHAIN', symbol: 'VET', color: '#15BDFF', tier: PopularityTier.C, sector: Sector.L1, chain: Chain.OTHER },
  { id: 'near', name: 'NEAR', symbol: 'NEAR', color: '#000000', tier: PopularityTier.B, sector: Sector.L1, chain: Chain.OTHER },
  { id: 'qnt', name: 'QUANT', symbol: 'QNT', color: '#000000', tier: PopularityTier.C, sector: Sector.INFRA, chain: Chain.ETHEREUM },
  { id: 'mkr', name: 'MAKER', symbol: 'MKR', color: '#1AAB9B', tier: PopularityTier.C, sector: Sector.DEFI, chain: Chain.ETHEREUM },
  { id: 'op', name: 'OPTIMISM', symbol: 'OP', color: '#FF0420', tier: PopularityTier.C, sector: Sector.L2, chain: Chain.ETHEREUM },
  { id: 'grt', name: 'THE GRAPH', symbol: 'GRT', color: '#6747ED', tier: PopularityTier.C, sector: Sector.INFRA, chain: Chain.ETHEREUM },
  { id: 'aave', name: 'AAVE', symbol: 'AAVE', color: '#B6509E', tier: PopularityTier.B, sector: Sector.DEFI, chain: Chain.ETHEREUM },
  { id: 'algo', name: 'ALGORAND', symbol: 'ALGO', color: '#000000', tier: PopularityTier.C, sector: Sector.L1, chain: Chain.OTHER },
  { id: 'axs', name: 'AXIE INFINITY', symbol: 'AXS', color: '#0055D5', tier: PopularityTier.C, sector: Sector.GAMING, chain: Chain.ETHEREUM },
  { id: 'sand', name: 'SANDBOX', symbol: 'SAND', color: '#00ADEF', tier: PopularityTier.C, sector: Sector.GAMING, chain: Chain.ETHEREUM },
  { id: 'mana', name: 'DECENTRALAND', symbol: 'MANA', color: '#FF2D55', tier: PopularityTier.C, sector: Sector.GAMING, chain: Chain.ETHEREUM },
  { id: 'eos', name: 'EOS', symbol: 'EOS', color: '#000000', tier: PopularityTier.C, sector: Sector.L1, chain: Chain.OTHER },
  { id: 'xtz', name: 'TEZOS', symbol: 'XTZ', color: '#2C7DF7', tier: PopularityTier.C, sector: Sector.L1, chain: Chain.OTHER },
  { id: 'theta', name: 'THETA', symbol: 'THETA', color: '#2AB8E6', tier: PopularityTier.C, sector: Sector.INFRA, chain: Chain.OTHER },
  { id: 'egld', name: 'MULTIVERSX', symbol: 'EGLD', color: '#23F6E7', tier: PopularityTier.C, sector: Sector.L1, chain: Chain.OTHER, legacyNames: ['ELROND'] },
  { id: 'imx', name: 'IMMUTABLE', symbol: 'IMX', color: '#0D0D0D', tier: PopularityTier.C, sector: Sector.GAMING, chain: Chain.ETHEREUM },
  { id: 'ftm', name: 'FANTOM', symbol: 'FTM', color: '#1969FF', tier: PopularityTier.C, sector: Sector.L1, chain: Chain.OTHER },

  // --- TIER C: Mid-Caps (Rank 51-150) ---
  { id: 'flow', name: 'FLOW', symbol: 'FLOW', color: '#00EF8B', tier: PopularityTier.C, sector: Sector.L1, chain: Chain.OTHER },
  { id: 'kava', name: 'KAVA', symbol: 'KAVA', color: '#FF564F', tier: PopularityTier.C, sector: Sector.DEFI, chain: Chain.COSMOS },
  { id: 'chz', name: 'CHILIZ', symbol: 'CHZ', color: '#CD0124', tier: PopularityTier.C, sector: Sector.GAMING, chain: Chain.OTHER },
  { id: 'curve', name: 'CURVE DAO', symbol: 'CRV', color: '#FF6B6B', tier: PopularityTier.C, sector: Sector.DEFI, chain: Chain.ETHEREUM },
  { id: 'neo', name: 'NEO', symbol: 'NEO', color: '#00E599', tier: PopularityTier.C, sector: Sector.L1, chain: Chain.OTHER },
  { id: 'gala', name: 'GALA', symbol: 'GALA', color: '#001E50', tier: PopularityTier.C, sector: Sector.GAMING, chain: Chain.ETHEREUM },
  { id: 'klay', name: 'KLAYTN', symbol: 'KLAY', color: '#FF3300', tier: PopularityTier.C, sector: Sector.L1, chain: Chain.OTHER },
  { id: 'iota', name: 'IOTA', symbol: 'IOTA', color: '#242424', tier: PopularityTier.D, sector: Sector.L1, chain: Chain.OTHER },
  { id: 'snx', name: 'SYNTHETIX', symbol: 'SNX', color: '#00D1FF', tier: PopularityTier.C, sector: Sector.DEFI, chain: Chain.ETHEREUM },
  { id: 'lunc', name: 'TERRA CLASSIC', symbol: 'LUNC', color: '#FFD83D', tier: PopularityTier.C, sector: Sector.L1, chain: Chain.OTHER },
  { id: 'mina', name: 'MINA', symbol: 'MINA', color: '#FF603B', tier: PopularityTier.D, sector: Sector.L1, chain: Chain.OTHER },
  { id: 'frx', name: 'FRAX SHARE', symbol: 'FXS', color: '#000000', tier: PopularityTier.D, sector: Sector.DEFI, chain: Chain.ETHEREUM },
  { id: 'cfx', name: 'CONFLUX', symbol: 'CFX', color: '#1E3DE4', tier: PopularityTier.C, sector: Sector.L1, chain: Chain.OTHER },
  { id: 'rpl', name: 'ROCKET POOL', symbol: 'RPL', color: '#FF8A00', tier: PopularityTier.C, sector: Sector.DEFI, chain: Chain.ETHEREUM },
  { id: 'nexo', name: 'NEXO', symbol: 'NEXO', color: '#1A4199', tier: PopularityTier.C, sector: Sector.DEFI, chain: Chain.OTHER },
  { id: 'gt', name: 'GATE TOKEN', symbol: 'GT', color: '#C63434', tier: PopularityTier.C, sector: Sector.EXCHANGE, chain: Chain.OTHER },
  { id: 'usdd', name: 'USDD', symbol: 'USDD', color: '#18314F', tier: PopularityTier.C, sector: Sector.STABLECOIN, chain: Chain.OTHER },
  { id: 'pepe', name: 'PEPE', symbol: 'PEPE', color: '#32CD32', tier: PopularityTier.C, sector: Sector.MEME, chain: Chain.ETHEREUM },
  { id: 'floki', name: 'FLOKI', symbol: 'FLOKI', color: '#FEF403', tier: PopularityTier.D, sector: Sector.MEME, chain: Chain.BSC },
  { id: 'dash', name: 'DASH', symbol: 'DASH', color: '#008CE7', tier: PopularityTier.D, sector: Sector.L1, chain: Chain.OTHER },
  { id: 'zec', name: 'ZCASH', symbol: 'ZEC', color: '#ECB244', tier: PopularityTier.D, sector: Sector.L1, chain: Chain.OTHER },
  { id: 'xec', name: 'ECASH', symbol: 'XEC', color: '#212C42', tier: PopularityTier.D, sector: Sector.L1, chain: Chain.OTHER },
  { id: 'cake', name: 'PANCAKESWAP', symbol: 'CAKE', color: '#D1884F', tier: PopularityTier.C, sector: Sector.DEX, chain: Chain.BSC },
  { id: '1inch', name: '1INCH', symbol: '1INCH', color: '#1B314F', tier: PopularityTier.D, sector: Sector.DEX, chain: Chain.ETHEREUM },
  { id: 'rune', name: 'THORCHAIN', symbol: 'RUNE', color: '#33FF99', tier: PopularityTier.C, sector: Sector.DEFI, chain: Chain.OTHER },
  { id: 'dydx', name: 'DYDX', symbol: 'DYDX', color: '#6966FF', tier: PopularityTier.C, sector: Sector.DEX, chain: Chain.ETHEREUM },
  { id: 'cvx', name: 'CONVEX', symbol: 'CVX', color: '#FF5C28', tier: PopularityTier.D, sector: Sector.DEFI, chain: Chain.ETHEREUM },
  { id: 'zil', name: 'ZILLIQA', symbol: 'ZIL', color: '#49C1BF', tier: PopularityTier.D, sector: Sector.L1, chain: Chain.OTHER },
  { id: 'gmx', name: 'GMX', symbol: 'GMX', color: '#2D42FC', tier: PopularityTier.C, sector: Sector.DEX, chain: Chain.ETHEREUM },
  { id: 'woo', name: 'WOO NETWORK', symbol: 'WOO', color: '#000000', tier: PopularityTier.D, sector: Sector.EXCHANGE, chain: Chain.OTHER },
  { id: 'bat', name: 'BAT', symbol: 'BAT', color: '#FF5000', tier: PopularityTier.C, sector: Sector.INFRA, chain: Chain.ETHEREUM, aliases: ['BASIC ATTENTION'] },
  { id: 'ar', name: 'ARWEAVE', symbol: 'AR', color: '#222222', tier: PopularityTier.D, sector: Sector.INFRA, chain: Chain.OTHER },
  { id: 'enj', name: 'ENJIN', symbol: 'ENJ', color: '#7866D5', tier: PopularityTier.C, sector: Sector.GAMING, chain: Chain.ETHEREUM },
  { id: 'mina', name: 'MINA PROTOCOL', symbol: 'MINA', color: '#FF603B', tier: PopularityTier.D, sector: Sector.L1, chain: Chain.OTHER },
  { id: 'qtum', name: 'QTUM', symbol: 'QTUM', color: '#2E9AD0', tier: PopularityTier.D, sector: Sector.L1, chain: Chain.OTHER },
  { id: 'celo', name: 'CELO', symbol: 'CELO', color: '#35D07F', tier: PopularityTier.C, sector: Sector.L1, chain: Chain.OTHER },
  { id: 'ksm', name: 'KUSAMA', symbol: 'KSM', color: '#000000', tier: PopularityTier.C, sector: Sector.L1, chain: Chain.DOT },
  { id: 'one', name: 'HARMONY', symbol: 'ONE', color: '#00AEE9', tier: PopularityTier.D, sector: Sector.L1, chain: Chain.OTHER },
  { id: 'audio', name: 'AUDIUS', symbol: 'AUDIO', color: '#CC00FF', tier: PopularityTier.D, sector: Sector.INFRA, chain: Chain.SOLANA },
  { id: 'hot', name: 'HOLO', symbol: 'HOT', color: '#00A6E3', tier: PopularityTier.D, sector: Sector.INFRA, chain: Chain.OTHER },
  { id: 'glmr', name: 'MOONBEAM', symbol: 'GLMR', color: '#E1147B', tier: PopularityTier.D, sector: Sector.L1, chain: Chain.DOT },
  { id: 'rose', name: 'OASIS NETWORK', symbol: 'ROSE', color: '#0057B8', tier: PopularityTier.D, sector: Sector.L1, chain: Chain.OTHER },
  
  // --- TIER D: Deeper Cuts (Rank 151-300) ---
  { id: 'ocean', name: 'OCEAN', symbol: 'OCEAN', color: '#000000', tier: PopularityTier.D, sector: Sector.AI, chain: Chain.ETHEREUM },
  { id: 'fet', name: 'FETCH AI', symbol: 'FET', color: '#1E2336', tier: PopularityTier.D, sector: Sector.AI, chain: Chain.ETHEREUM },
  { id: 'agix', name: 'SINGULARITY', symbol: 'AGIX', color: '#6816D3', tier: PopularityTier.D, sector: Sector.AI, chain: Chain.ETHEREUM },
  { id: 'rndr', name: 'RENDER', symbol: 'RNDR', color: '#FF2E2E', tier: PopularityTier.C, sector: Sector.INFRA, chain: Chain.SOLANA },
  { id: 'dcr', name: 'DECRED', symbol: 'DCR', color: '#2ED6A1', tier: PopularityTier.D, sector: Sector.L1, chain: Chain.OTHER },
  { id: 'waves', name: 'WAVES', symbol: 'WAVES', color: '#0155FF', tier: PopularityTier.D, sector: Sector.L1, chain: Chain.OTHER },
  { id: 'rvn', name: 'RAVENCOIN', symbol: 'RVN', color: '#384182', tier: PopularityTier.D, sector: Sector.L1, chain: Chain.OTHER },
  { id: 'ont', name: 'ONTOLOGY', symbol: 'ONT', color: '#32A4BE', tier: PopularityTier.D, sector: Sector.L1, chain: Chain.OTHER },
  { id: 'omg', name: 'OMG NETWORK', symbol: 'OMG', color: '#101010', tier: PopularityTier.D, sector: Sector.L2, chain: Chain.ETHEREUM },
  { id: 'zrx', name: '0X', symbol: 'ZRX', color: '#000000', tier: PopularityTier.D, sector: Sector.INFRA, chain: Chain.ETHEREUM },
  { id: 'skl', name: 'SKALE', symbol: 'SKL', color: '#000000', tier: PopularityTier.D, sector: Sector.L2, chain: Chain.ETHEREUM },
  { id: 'waxp', name: 'WAX', symbol: 'WAXP', color: '#F08900', tier: PopularityTier.D, sector: Sector.GAMING, chain: Chain.OTHER },
  { id: 'sc', name: 'SIACOIN', symbol: 'SC', color: '#00CBA0', tier: PopularityTier.D, sector: Sector.INFRA, chain: Chain.OTHER },
  { id: 'ankr', name: 'ANKR', symbol: 'ANKR', color: '#2E6BED', tier: PopularityTier.D, sector: Sector.INFRA, chain: Chain.ETHEREUM },
  { id: 'gno', name: 'GNOSIS', symbol: 'GNO', color: '#001428', tier: PopularityTier.D, sector: Sector.INFRA, chain: Chain.ETHEREUM },
  { id: 'sushi', name: 'SUSHI', symbol: 'SUSHI', color: '#FA52A0', tier: PopularityTier.C, sector: Sector.DEX, chain: Chain.ETHEREUM },
  { id: 'yfi', name: 'YEARN', symbol: 'YFI', color: '#006AE3', tier: PopularityTier.C, sector: Sector.DEFI, chain: Chain.ETHEREUM },
  { id: 'comp', name: 'COMPOUND', symbol: 'COMP', color: '#00D395', tier: PopularityTier.C, sector: Sector.DEFI, chain: Chain.ETHEREUM },
  { id: 'bal', name: 'BALANCER', symbol: 'BAL', color: '#1E1E1E', tier: PopularityTier.D, sector: Sector.DEFI, chain: Chain.ETHEREUM },
  { id: 'sxp', name: 'SOLAR', symbol: 'SXP', color: '#FD5621', tier: PopularityTier.D, sector: Sector.L1, chain: Chain.OTHER },
  { id: 'band', name: 'BAND', symbol: 'BAND', color: '#516AFF', tier: PopularityTier.D, sector: Sector.ORACLE, chain: Chain.COSMOS },
  { id: 'kda', name: 'KADENA', symbol: 'KDA', color: '#ED098F', tier: PopularityTier.D, sector: Sector.L1, chain: Chain.OTHER },
  { id: 'lsk', name: 'LISK', symbol: 'LSK', color: '#0D4EA0', tier: PopularityTier.D, sector: Sector.L1, chain: Chain.OTHER },
  { id: 'nano', name: 'NANO', symbol: 'XNO', color: '#4A90E2', tier: PopularityTier.D, sector: Sector.L1, chain: Chain.OTHER },
  { id: 'zen', name: 'HORIZEN', symbol: 'ZEN', color: '#041742', tier: PopularityTier.D, sector: Sector.L1, chain: Chain.OTHER },
  { id: 'glm', name: 'GOLEM', symbol: 'GLM', color: '#181E6D', tier: PopularityTier.D, sector: Sector.INFRA, chain: Chain.ETHEREUM },
  { id: 'flux', name: 'FLUX', symbol: 'FLUX', color: '#2B61D1', tier: PopularityTier.D, sector: Sector.INFRA, chain: Chain.OTHER },
  { id: 'sys', name: 'SYSCOIN', symbol: 'SYS', color: '#0082C6', tier: PopularityTier.D, sector: Sector.L1, chain: Chain.OTHER },
  { id: 'hive', name: 'HIVE', symbol: 'HIVE', color: '#FF112D', tier: PopularityTier.D, sector: Sector.L1, chain: Chain.OTHER },
  { id: 'steem', name: 'STEEM', symbol: 'STEEM', color: '#1A5099', tier: PopularityTier.D, sector: Sector.L1, chain: Chain.OTHER },
  { id: 'strax', name: 'STRATIS', symbol: 'STRAX', color: '#118DXB', tier: PopularityTier.D, sector: Sector.L1, chain: Chain.OTHER },
  { id: 'movr', name: 'MOONRIVER', symbol: 'MOVR', color: '#F2B705', tier: PopularityTier.D, sector: Sector.L1, chain: Chain.DOT },
  { id: 'ckb', name: 'NERVOS', symbol: 'CKB', color: '#000000', tier: PopularityTier.D, sector: Sector.L1, chain: Chain.OTHER },
  { id: 'uma', name: 'UMA', symbol: 'UMA', color: '#FF4A4A', tier: PopularityTier.D, sector: Sector.DEFI, chain: Chain.ETHEREUM },
  { id: 'pla', name: 'PLAYDAPP', symbol: 'PLA', color: '#1A1A1A', tier: PopularityTier.D, sector: Sector.GAMING, chain: Chain.ETHEREUM },
  { id: 'api3', name: 'API3', symbol: 'API3', color: '#000000', tier: PopularityTier.D, sector: Sector.ORACLE, chain: Chain.ETHEREUM },
  { id: 'rlc', name: 'IEXEC RLC', symbol: 'RLC', color: '#FFD800', tier: PopularityTier.D, sector: Sector.INFRA, chain: Chain.ETHEREUM },
  { id: 'nmr', name: 'NUMERAIRE', symbol: 'NMR', color: '#000000', tier: PopularityTier.D, sector: Sector.AI, chain: Chain.ETHEREUM },
  { id: 'storj', name: 'STORJ', symbol: 'STORJ', color: '#2683FF', tier: PopularityTier.D, sector: Sector.INFRA, chain: Chain.ETHEREUM },
  { id: 'ogn', name: 'ORIGIN', symbol: 'OGN', color: '#1A82FF', tier: PopularityTier.D, sector: Sector.NFT, chain: Chain.ETHEREUM },
  { id: 'pundix', name: 'PUNDI X', symbol: 'PUNDIX', color: '#F7E300', tier: PopularityTier.D, sector: Sector.INFRA, chain: Chain.OTHER },
  { id: 'dent', name: 'DENT', symbol: 'DENT', color: '#666666', tier: PopularityTier.D, sector: Sector.INFRA, chain: Chain.ETHEREUM },
];
